import { create } from 'zustand';

export type TaskStatus = 'Pending' | 'In Progress' | 'Blocked' | 'Completed' | 'Closed';
export type TaskPriority = 'Critical' | 'High' | 'Medium' | 'Low';
export type TaskType = 'Sales' | 'Operations' | 'Content' | 'Support' | 'Follow-up' | 'Finance' | 'Admin' | 'HR' | 'Other';
export type Department = 'Sales' | 'Operations' | 'Content' | 'Support' | 'Finance' | 'Admin' | 'HR';

export interface TaskChecklistItem {
  id: string;
  label: string;
  completed: boolean;
}

export interface TaskActivity {
  id: string;
  timestamp: string;
  user: string;
  action: string;
}

export interface TaskRemark {
  id?: string;
  text: string;
  statusAtTime?: string;
  user?: any;
  userName?: string;
  createdAt: string;
}

export interface Task {
  id: string;
  _id?: string;
  title: string;
  description: string;
  type: TaskType;
  department: Department;
  category?: string;
  taskType?: string;
  priority: TaskPriority;
  status: TaskStatus;
  assignedTo: any;
  createdBy: any;
  createdAt: string;
  startDate?: string;
  dueDate: string;
  dueTime?: string;
  relatedTo?: string; // e.g. Lead: ABC Pvt Ltd
  tags: string[];
  checklist: TaskChecklistItem[];
  activities: TaskActivity[];
  remark?: string;
  remarkUpdatedAt?: string;
  remarkUpdatedBy?: any;
  remarks?: TaskRemark[];
}

interface TasksState {
  tasks: Task[];
  fetchTasks: (params?: any) => Promise<void>;
  addTask: (task: any) => Promise<void>;
  updateTask: (id: string, updates: any) => Promise<void>;
  addRemark: (id: string, remark: string, status?: string) => Promise<void>;
  deleteTask: (id: string) => Promise<void>;
  addActivity: (taskId: string, activity: any) => Promise<void>;
  toggleChecklistItem: (taskId: string, checklistItemId: string) => Promise<void>;
}

import { tasksApi } from '../lib/api-client';
import { toast } from 'sonner';

export const useTasksStore = create<TasksState>((set, get) => ({
  tasks: [],
  fetchTasks: async (params) => {
    try {
      const res = await tasksApi.list(params);
      set({ tasks: res.data.data });
    } catch (error) {
      console.error('Failed to fetch tasks', error);
      toast.error('Failed to fetch tasks');
    }
  },
  addTask: async (taskData) => {
    try {
      const res = await tasksApi.create(taskData);
      set((state) => ({ tasks: [res.data.data, ...state.tasks] }));
      toast.success('Task created successfully');
    } catch (error) {
      toast.error('Failed to create task');
      throw error;
    }
  },
  updateTask: async (id, updates) => {
    try {
      const res = await tasksApi.update(id, updates);
      set((state) => ({
        tasks: state.tasks.map((t: any) => ((t._id || t.id) === id ? res.data.data : t))
      }));
      toast.success('Task updated');
    } catch (error) {
      toast.error('Failed to update task');
      throw error;
    }
  },
  addRemark: async (id, remark, status) => {
    try {
      const res = await tasksApi.addRemark(id, { remark, status });
      set((state) => ({
        tasks: state.tasks.map((t: any) => ((t._id || t.id) === id ? res.data.data : t))
      }));
      toast.success('Remark added successfully');
    } catch (error) {
      toast.error('Failed to add remark');
      throw error;
    }
  },
  deleteTask: async (id) => {
    try {
      await tasksApi.delete(id);
      set((state) => ({
        tasks: state.tasks.filter((t: any) => (t._id || t.id) !== id)
      }));
      toast.success('Task deleted');
    } catch (error) {
      toast.error('Failed to delete task');
      throw error;
    }
  },
  addActivity: async (taskId, activityData) => {
    // Activities are mostly auto-generated by the backend, 
    // but if it's a comment, we use the addComment API.
    if (activityData.action === 'commented') {
      try {
        const res = await tasksApi.addComment(taskId, { message: (activityData as any).details?.message || activityData.action });
        // Refetch or update local state manually
        // For simplicity, we just update the specific task's comments in the state if needed, 
        // but ideally we should fetch the task again.
        get().fetchTasks(); 
      } catch (error) {
        toast.error('Failed to add comment');
      }
    }
  },
  toggleChecklistItem: async (taskId, checklistItemId) => {
    try {
      // Find current item
      const task = get().tasks.find((t: any) => (t._id || t.id) === taskId);
      const item = task?.checklist?.find(c => c.id === checklistItemId);
      if (!item) return;

      await tasksApi.updateChecklist(taskId, { id: checklistItemId, isCompleted: !item.completed });
      get().fetchTasks();
    } catch (error) {
      toast.error('Failed to update checklist');
    }
  }
}));
