'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import {
  ClipboardCheck,
  Search,
  Eye,
  CheckCircle2,
  XCircle,
  MessageSquare,
  ShieldCheck,
  Clock,
  ArrowRight,
  Globe,
  Edit2,
} from 'lucide-react';
import { useAiContentStore, AiContentItem } from '@/stores/ai-content';
import { QualityScoreBadge } from '@/components/ai-content/quality-score-badge';
import { ReviewDetailModal } from '@/components/ai-content/review-detail-modal';
import { PublishConfirmationModal } from '@/components/ai-content/publish-confirmation-modal';

export default function ReviewApprovalPage() {
  const router = useRouter();
  const { items, approveContent, rejectContent, requestChanges, publishToCms } = useAiContentStore();

  const [search, setSearch] = useState('');
  const [activeReviewItem, setActiveReviewItem] = useState<AiContentItem | null>(null);
  const [activePublishItem, setActivePublishItem] = useState<AiContentItem | null>(null);

  // Review & Approval Queue shows items in Pending Review, Changes Requested, or Approved
  const reviewQueue = items.filter((item) => {
    const matchesSearch =
      item.contentId?.toLowerCase().includes(search.toLowerCase()) ||
      item.id?.toLowerCase().includes(search.toLowerCase()) ||
      item.title.toLowerCase().includes(search.toLowerCase()) ||
      item.productName?.toLowerCase().includes(search.toLowerCase()) ||
      item.submittedBy?.toLowerCase().includes(search.toLowerCase());

    return matchesSearch;
  });

  const pendingCount = items.filter((i) => i.status === 'Pending Review').length;
  const approvedCount = items.filter((i) => i.status === 'Approved').length;

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b pb-4">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-2xl font-bold tracking-tight text-foreground">
              Review & Approval
            </h1>
            <Badge variant="outline" className="bg-primary/5 text-primary border-primary/20 text-xs">
              Quality Gatekeeper
            </Badge>
          </div>
          <p className="text-sm text-muted-foreground mt-1">
            Mandatory human review gate before content can be published to the CMS. Compare AI baseline against edits.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <div className="flex items-center gap-1.5 bg-blue-500/10 border border-blue-500/20 text-blue-600 px-3 py-1.5 rounded-lg text-xs font-semibold">
            <Clock className="w-3.5 h-3.5" />
            <span>{pendingCount} Awaiting Review</span>
          </div>
          <div className="flex items-center gap-1.5 bg-emerald-500/10 border border-emerald-500/20 text-emerald-600 px-3 py-1.5 rounded-lg text-xs font-semibold">
            <CheckCircle2 className="w-3.5 h-3.5" />
            <span>{approvedCount} Approved</span>
          </div>
        </div>
      </div>

      {/* Review Queue Table (Section 11) */}
      <div className="bg-card border rounded-xl overflow-hidden shadow-sm space-y-3 p-4">
        <div className="flex items-center justify-between gap-3 pb-2">
          <div className="relative flex-1 max-w-sm">
            <Search className="w-4 h-4 absolute left-3 top-2.5 text-muted-foreground" />
            <Input
              placeholder="Search approval queue..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="pl-9 text-xs h-9"
            />
          </div>
          <span className="text-xs text-muted-foreground">
            Strict human review workflow: AI never publishes directly.
          </span>
        </div>

        <div className="border rounded-lg overflow-x-auto">
          <table className="w-full text-xs text-left">
            <thead className="bg-muted/40 border-b text-muted-foreground uppercase tracking-wider text-[11px] font-semibold">
              <tr>
                <th className="py-3 px-4 whitespace-nowrap">Content ID</th>
                <th className="py-3 px-4 whitespace-nowrap">Type</th>
                <th className="py-3 px-4 whitespace-nowrap">Product / Campaign</th>
                <th className="py-3 px-4 whitespace-nowrap">Submitted By</th>
                <th className="py-3 px-4 whitespace-nowrap">Submitted Date</th>
                <th className="py-3 px-4 whitespace-nowrap">AI Generated By</th>
                <th className="py-3 px-4 whitespace-nowrap">Status</th>
                <th className="py-3 px-4 whitespace-nowrap">Reviewer</th>
                <th className="py-3 px-4 text-right whitespace-nowrap">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {reviewQueue.length === 0 ? (
                <tr>
                  <td colSpan={9} className="py-12 text-center text-muted-foreground text-xs">
                    No records in the approval queue.
                  </td>
                </tr>
              ) : (
                reviewQueue.map((item) => {
                  const isPending = item.status === 'Pending Review';
                  const isApproved = item.status === 'Approved';

                  return (
                    <tr key={item.id} className="hover:bg-muted/20 transition-colors">
                      <td className="py-3 px-4 font-mono font-semibold text-foreground whitespace-nowrap">
                        {item.id}
                      </td>

                      <td className="py-3 px-4 whitespace-nowrap">
                        <Badge variant="secondary" className="text-[10px] capitalize font-medium">
                          {item.contentType.replace('_', ' ')}
                        </Badge>
                      </td>

                      <td className="py-3 px-4 whitespace-nowrap">
                        <div className="font-semibold text-foreground whitespace-nowrap">{item.productName}</div>
                        <div className="text-[10px] text-muted-foreground whitespace-nowrap">{item.sku || item.channel || '—'}</div>
                      </td>

                      <td className="py-3 px-4 whitespace-nowrap text-muted-foreground">
                        {item.submittedBy || item.createdBy}
                      </td>

                      <td className="py-3 px-4 whitespace-nowrap text-muted-foreground">
                        {item.submittedAt || item.createdAt.slice(0, 10)}
                      </td>

                      <td className="py-3 px-4 whitespace-nowrap text-muted-foreground">
                        JODO AI Engine
                      </td>

                      <td className="py-3 px-4 whitespace-nowrap">
                        <span
                          className={`inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-semibold border ${
                            item.status === 'Approved'
                              ? 'bg-emerald-500/10 text-emerald-600 border-emerald-500/20'
                              : item.status === 'Pending Review'
                              ? 'bg-blue-500/10 text-blue-600 border-blue-500/20'
                              : item.status === 'Published'
                              ? 'bg-purple-500/10 text-purple-600 border-purple-500/20'
                              : item.status === 'Changes Requested'
                              ? 'bg-amber-500/10 text-amber-600 border-amber-500/20'
                              : 'bg-muted text-muted-foreground'
                          }`}
                        >
                          {item.status}
                        </span>
                      </td>

                      <td className="py-3 px-4 whitespace-nowrap text-muted-foreground">
                        {item.approvedBy || item.reviewedBy || 'Unassigned'}
                      </td>

                      <td className="py-3 px-4 text-right whitespace-nowrap">
                        <div className="flex items-center justify-end gap-1.5">
                          {/* Preview modal with diff & comparison */}
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => setActiveReviewItem(item)}
                            className="h-7 text-xs px-2.5 gap-1"
                          >
                            <Eye className="w-3 h-3 text-primary" />
                            Preview
                          </Button>

                          {/* Quick Approve button if pending */}
                          {isPending && (
                            <Button
                              size="sm"
                              onClick={() => approveContent(item.id, 'Lead Editor')}
                              className="h-7 text-xs px-2.5 bg-emerald-600 hover:bg-emerald-700 text-white gap-1"
                            >
                              <CheckCircle2 className="w-3 h-3" />
                              Approve
                            </Button>
                          )}

                          {/* STRICT RULE: Only Approved content displays Publish to CMS */}
                          {isApproved && (
                            <Button
                              size="sm"
                              onClick={() => setActivePublishItem(item)}
                              className="h-7 text-xs px-2.5 bg-emerald-600 hover:bg-emerald-700 text-white gap-1 shadow-sm"
                            >
                              <Globe className="w-3 h-3" />
                              Publish to CMS
                            </Button>
                          )}
                        </div>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Review Detail Modal */}
      {activeReviewItem && (
        <ReviewDetailModal
          isOpen={!!activeReviewItem}
          onClose={() => setActiveReviewItem(null)}
          item={activeReviewItem}
          onApprove={(id) => approveContent(id, 'Lead Reviewer')}
          onRequestChanges={(id, feedback) => requestChanges(id, feedback)}
          onReject={(id, reason) => rejectContent(id, reason)}
        />
      )}

      {/* Publish Confirmation Modal */}
      {activePublishItem && (
        <PublishConfirmationModal
          isOpen={!!activePublishItem}
          onClose={() => setActivePublishItem(null)}
          onConfirm={async () => {
            await publishToCms(activePublishItem.id, 'Admin');
          }}
          item={activePublishItem}
        />
      )}
    </div>
  );
}
